<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Survey Response #{{ $response->id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #1f2937;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 10px;
        }
        h2 {
            color: #374151;
            margin-top: 20px;
            border-bottom: 1px solid #d1d5db;
            padding-bottom: 8px;
        }
        .section {
            margin: 20px 0;
            padding: 15px;
            background-color: #f9fafb;
            border-left: 4px solid #2563eb;
        }
        .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin: 15px 0;
        }
        .info-item {
            padding: 10px;
            background-color: #fff;
            border: 1px solid #e5e7eb;
            border-radius: 4px;
        }
        .label {
            font-weight: bold;
            color: #2563eb;
            font-size: 12px;
            text-transform: uppercase;
        }
        .value {
            font-size: 14px;
            color: #1f2937;
            margin-top: 5px;
        }
        .answer-item {
            margin: 15px 0;
            padding: 10px;
            background-color: #fff;
            border: 1px solid #e5e7eb;
            border-radius: 4px;
        }
        .question-number {
            display: inline-block;
            background-color: #2563eb;
            color: white;
            width: 24px;
            height: 24px;
            border-radius: 50%;
            text-align: center;
            line-height: 24px;
            font-weight: bold;
            margin-right: 10px;
        }
        footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #d1d5db;
            text-align: center;
            font-size: 11px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <h1>Awaam ki Awaaz Response Report</h1>
    <p>Response ID: <strong>#{{ $response->id }}</strong></p>
    <p>Date: <strong>{{ $response->created_at->format('M d, Y') }}</strong></p>

    <div class="section">
        <h2>Student Profile</h2>
        <div class="info-grid">
            <div class="info-item">
                <div class="label">Age Group</div>
                <div class="value">{{ $response->age_group }}</div>
            </div>
            <div class="info-item">
                <div class="label">Gender</div>
                <div class="value">{{ $response->gender }}</div>
            </div>
            <div class="info-item">
                <div class="label">Education</div>
                <div class="value">{{ $response->education }}</div>
            </div>
            <div class="info-item">
                <div class="label">Occupation</div>
                <div class="value">{{ $response->occupation }}</div>
            </div>
        </div>
        <div class="info-grid">
            <div class="info-item">
                <div class="label">Tech Usage</div>
                <div class="value">{{ $response->tech_usage }}</div>
            </div>
            <div class="info-item">
                <div class="label">AI Usage</div>
                <div class="value">{{ $response->ai_usage }}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Survey Responses</h2>
        @forelse($questions as $index => $question)
            <div class="answer-item">
                <span class="question-number">{{ $index + 1 }}</span>
                <strong>Question {{ $index + 1 }}</strong><br>
                {{ $question['q'] }}<br><br>
                <strong>Selected answer:</strong> {{ $response->selected_answers[$index] ?? 'Not answered' }}
            </div>
        @empty
            <p>No survey responses recorded.</p>
        @endforelse
    </div>

    <footer>
        <p>This report was automatically generated by the Awaam ki Awaaz system.</p>
        <p>All information is confidential and used only for research purposes.</p>
        <p>Made with 💚 by Muhammad Sufyan Jura</p>
    </footer>
</body>
</html>